[BUGFIX] switch to excel package: phpoffice/phpspreadsheet
sirdiego/importr pull request #37
Opened 2023-01-25 21:27 UTC by lochmueller

2023-01-31 19:18 UTC, lochmueller commented
@sirdiego Do you need more information for this PR?

2023-01-31 19:30 UTC, sirdiego commented
@lochmueller yeah see my review comment above

2023-01-31 19:46 UTC, lochmueller commented
Hmm... I saw no comment?!

2023-02-01 15:10 UTC, sirdiego requested changes

2023-02-01 15:10 UTC, sirdiego commented on Classes/Service/Resources/Excel.php
> +        $filename = Environment::getPublicPath() . $this->filepath;
Hi @lochmueller,
why did you change this line? This would NOT have the same effect. I think we originally used this call to e.g. resolve "EXT:" prefixes, when we now just concatenate this with the filepath that would be something completely different. getFileAbsFileName is also not deprecated 🤔
I'd like to have a little more input on this, thanks!

2023-02-01 17:48 UTC, lochmueller commented
Hey @sirdiego the problem in my case was, that "$this->filepath" starts with a "/" but was relative to the docroot. As result the GeneralUtility::getFileAbsFileName() remove the path, because it is no "real" absolute path. I think there are changes in the path handling between the versions. `Environment::getPublicPath()` looks ok for me, because it exists since v10.
Regards, Tim

2026-07-22 20:02 UTC, closed without merging